
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "account.h" */


GType purple_account_request_response_get_type (void);
#define PURPLE_TYPE_ACCOUNT_REQUEST_RESPONSE (purple_account_request_response_get_type())


GType purple_account_privacy_type_get_type (void);
#define PURPLE_TYPE_ACCOUNT_PRIVACY_TYPE (purple_account_privacy_type_get_type())

/* enumerations from "buddyicon.h" */


GType purple_buddy_icon_scale_flags_get_type (void);
#define PURPLE_TYPE_BUDDY_ICON_SCALE_FLAGS (purple_buddy_icon_scale_flags_get_type())

/* enumerations from "connection.h" */


GType purple_connection_flags_get_type (void);
#define PURPLE_TYPE_CONNECTION_FLAGS (purple_connection_flags_get_type())


GType purple_connection_state_get_type (void);
#define PURPLE_TYPE_CONNECTION_STATE (purple_connection_state_get_type())

/* enumerations from "debug.h" */


GType purple_debug_level_get_type (void);
#define PURPLE_TYPE_DEBUG_LEVEL (purple_debug_level_get_type())

/* enumerations from "eventloop.h" */


GType purple_input_condition_get_type (void);
#define PURPLE_TYPE_INPUT_CONDITION (purple_input_condition_get_type())

/* enumerations from "notify.h" */


GType purple_notify_type_get_type (void);
#define PURPLE_TYPE_NOTIFY_TYPE (purple_notify_type_get_type())


GType purple_notify_message_type_get_type (void);
#define PURPLE_TYPE_NOTIFY_MESSAGE_TYPE (purple_notify_message_type_get_type())


GType purple_notify_search_button_type_get_type (void);
#define PURPLE_TYPE_NOTIFY_SEARCH_BUTTON_TYPE (purple_notify_search_button_type_get_type())


GType purple_notify_user_info_entry_type_get_type (void);
#define PURPLE_TYPE_NOTIFY_USER_INFO_ENTRY_TYPE (purple_notify_user_info_entry_type_get_type())

/* enumerations from "purplechatuser.h" */


GType purple_chat_user_flags_get_type (void);
#define PURPLE_TYPE_CHAT_USER_FLAGS (purple_chat_user_flags_get_type())

/* enumerations from "purpleconnectionerrorinfo.h" */


GType purple_connection_error_get_type (void);
#define PURPLE_TYPE_CONNECTION_ERROR (purple_connection_error_get_type())

/* enumerations from "purpleconversation.h" */


GType purple_conversation_update_type_get_type (void);
#define PURPLE_TYPE_CONVERSATION_UPDATE_TYPE (purple_conversation_update_type_get_type())

/* enumerations from "purpleimconversation.h" */


GType purple_im_typing_state_get_type (void);
#define PURPLE_TYPE_IM_TYPING_STATE (purple_im_typing_state_get_type())

/* enumerations from "purplemessage.h" */


GType purple_message_flags_get_type (void);
#define PURPLE_TYPE_MESSAGE_FLAGS (purple_message_flags_get_type())


GType purple_message_content_type_get_type (void);
#define PURPLE_TYPE_MESSAGE_CONTENT_TYPE (purple_message_content_type_get_type())

/* enumerations from "purplenotification.h" */


GType purple_notification_type_get_type (void);
#define PURPLE_TYPE_NOTIFICATION_TYPE (purple_notification_type_get_type())

/* enumerations from "purpleplugininfo.h" */


GType purple_plugin_info_flags_get_type (void);
#define PURPLE_TYPE_PLUGIN_INFO_FLAGS (purple_plugin_info_flags_get_type())

/* enumerations from "purpleprotocol.h" */


GType purple_protocol_options_get_type (void);
#define PURPLE_TYPE_PROTOCOL_OPTIONS (purple_protocol_options_get_type())

/* enumerations from "purpleproxyinfo.h" */


GType purple_proxy_type_get_type (void);
#define PURPLE_TYPE_PROXY_TYPE (purple_proxy_type_get_type())

/* enumerations from "roomlist.h" */


GType purple_roomlist_field_type_get_type (void);
#define PURPLE_TYPE_ROOMLIST_FIELD_TYPE (purple_roomlist_field_type_get_type())

/* enumerations from "status.h" */


GType purple_status_primitive_get_type (void);
#define PURPLE_TYPE_STATUS_PRIMITIVE (purple_status_primitive_get_type())

/* enumerations from "xfer.h" */


GType purple_xfer_type_get_type (void);
#define PURPLE_TYPE_XFER_TYPE (purple_xfer_type_get_type())


GType purple_xfer_status_get_type (void);
#define PURPLE_TYPE_XFER_STATUS (purple_xfer_status_get_type())

/* enumerations from "xmlnode.h" */


GType purple_xml_node_type_get_type (void);
#define PURPLE_TYPE_XML_NODE_TYPE (purple_xml_node_type_get_type())

G_END_DECLS

/* Generated data ends here */

